
name: daily run

on:
  schedule:

    - cron:  '46 21 * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm i
    - run: npm run run
