
name: daily run

on:
  schedule:
    - cron:  '49 * * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm i
    - name: run
      env: 
        NODE_DISCORD_TOKEN: ${{ secrets.NODE_DISCORD_TOKEN }}
      run: npm run run
